# NOTE: update this with your service name
service: crear-activa-backend

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:us-east-1:*:*'
    - Effect: Allow
      Action:
        - cloudformation:DescribeStackResource
      Resource: "*"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
          integration: LAMBDA
  create:
    handler: create.main
    events:
      - http:
          path: posts
          method: post
          authorizer: aws_iam
          cors: true
          integration: LAMBDA
  get:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /notes/{id}
    # - method: GET request
    handler: get.main
    events:
      - http:
          path: posts/{id}
          method: get
          authorizer: aws_iam
          cors: true
          integration: LAMBDA
  list-posts:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /notes
    # - method: GET request
    handler: list-posts.main
    events:
      - http:
          path: posts
          method: get
          authorizer: aws_iam
          cors: true
          integration: LAMBDA
  update-post:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is /notes/{id}
    # - method: PUT request
    handler: update-post.main
    events:
      - http:
          path: posts/{id}
          method: put
          authorizer: aws_iam
          cors: true
          integration: LAMBDA
  delete-post:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is /notes/{id}
    # - method: DELETE request
    handler: delete-post.main
    events:
      - http:
          path: posts/{id}
          method: delete
          authorizer: aws_iam
          cors: true
          integration: LAMBDA

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
